version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        auth:
          username: mfpx
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - cci-ecs713p-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - cci-ecs713p-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Install executable
          command: stack --no-terminal install
      - run:
          name: Run the project
          command: stack run
      - save_cache:
          name: Cache Dependencies
          key: cci-ecs713p-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - store_artifacts:
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ~/.local/bin/haskell-project
          destination: bin-export 